name = "Pengolod's comficraft Modpack"
author = "Pengolod"
version = "2021.11.17+1.18"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b48d25408996a406dc55c129e3c75896184579d8aeffe65cb4537b4d38702e1"

[versions]
fabric = "0.12.5"
minecraft = "1.18-pre4"

[options]
acceptable-game-versions = ["1.18-Snapshot", "21w37a", "21w38a", "21w39a", "21w40a", "21w41a", "21w42a", "21w43a", "21w44a", "1.18-pre1", "1.18-pre2", "1.18-pre3"]
