name = "Fabric API"
filename = "fabric-api-0.42.7+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3528/963/fabric-api-0.42.7+1.18.jar"
hash-format = "murmur2"
hash = "3295419612"

[update]
[update.curseforge]
file-id = 3528963
project-id = 306612
release-channel = "beta"
